# Generated by Django 5.2.9 on 2025-12-21 06:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ohsms', '0004_section'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='branch',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ohsms.branch', verbose_name='الفرع'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='incident',
            name='department',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ohsms.department', verbose_name='الإدارة'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='incident',
            name='section',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ohsms.section', verbose_name='القسم'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='incident',
            name='status',
            field=models.CharField(choices=[('open', 'مفتوح'), ('in_progress', 'قيد المعالجة'), ('closed', 'مغلق')], default='open', max_length=20, verbose_name='الحالة'),
        ),
        migrations.AlterField(
            model_name='incident',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء'),
        ),
        migrations.AlterField(
            model_name='incident',
            name='incident_type',
            field=models.CharField(choices=[('normal', 'بلاغ عادي'), ('urgent', 'بلاغ عاجل'), ('secret', 'بلاغ سري')], max_length=20, verbose_name='نوع البلاغ'),
        ),
    ]
