# Generated by Django 5.2.9 on 2025-12-23 08:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ohsms', '0005_incident_branch_incident_department_incident_section_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AffectedGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='الفئة المتأثرة')),
            ],
        ),
        migrations.CreateModel(
            name='FormField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=200, verbose_name='عنوان الحقل')),
                ('field_type', models.CharField(choices=[('text', 'نص'), ('number', 'رقم'), ('textarea', 'نص طويل'), ('select', 'اختيار'), ('radio', 'اختيار فردي'), ('checkbox', 'نعم / لا'), ('date', 'تاريخ')], max_length=20, verbose_name='نوع الحقل')),
                ('is_required', models.BooleanField(default=False, verbose_name='إلزامي')),
                ('order', models.PositiveSmallIntegerField(verbose_name='الترتيب')),
                ('options', models.TextField(blank=True, verbose_name='الخيارات (مفصولة بفواصل)')),
            ],
        ),
        migrations.CreateModel(
            name='FormSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitted_by', models.CharField(blank=True, max_length=200, verbose_name='مُعبئ النموذج')),
                ('submitted_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإرسال')),
            ],
        ),
        migrations.CreateModel(
            name='RiskCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='فئة الخطر الرئيسية')),
                ('description', models.TextField(blank=True, verbose_name='الوصف')),
            ],
        ),
        migrations.CreateModel(
            name='RiskCause',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='سبب الخطر')),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='كود الدور')),
                ('name', models.CharField(max_length=200, verbose_name='اسم الدور')),
                ('is_global', models.BooleanField(default=False, verbose_name='صلاحية شاملة (بدون نطاق)')),
                ('description', models.TextField(blank=True, verbose_name='وصف الدور')),
            ],
        ),
        migrations.CreateModel(
            name='SystemContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_type', models.CharField(choices=[('policy', 'سياسة السلامة'), ('objectives', 'الأهداف'), ('scope', 'نطاق النظام'), ('awareness', 'التوعية'), ('homepage', 'الصفحة الرئيسية'), ('incident_instructions', 'تعليمات البلاغات')], max_length=50, unique=True, verbose_name='نوع المحتوى')),
                ('title', models.CharField(max_length=200, verbose_name='العنوان')),
                ('body', models.TextField(verbose_name='المحتوى')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
            ],
        ),
        migrations.AddField(
            model_name='incident',
            name='handled_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاريخ بدء المعالجة'),
        ),
        migrations.CreateModel(
            name='FormAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField(verbose_name='الإجابة')),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ohsms.formfield', verbose_name='الحقل')),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='ohsms.formsubmission', verbose_name='التقديم')),
            ],
        ),
        migrations.CreateModel(
            name='FormTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='اسم النموذج')),
                ('description', models.TextField(blank=True, verbose_name='وصف النموذج')),
                ('visibility', models.CharField(choices=[('public', 'عام'), ('restricted', 'محدد')], default='restricted', max_length=20, verbose_name='نطاق النشر')),
                ('is_active', models.BooleanField(default=True, verbose_name='مفعل')),
                ('created_by', models.CharField(max_length=200, verbose_name='أنشئ بواسطة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ohsms.branch', verbose_name='الفرع')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ohsms.department', verbose_name='الإدارة')),
                ('section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ohsms.section', verbose_name='القسم')),
            ],
        ),
        migrations.AddField(
            model_name='formsubmission',
            name='form',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='ohsms.formtemplate', verbose_name='النموذج'),
        ),
        migrations.AddField(
            model_name='formfield',
            name='form',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='ohsms.formtemplate', verbose_name='النموذج'),
        ),
        migrations.CreateModel(
            name='IncidentEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('create', 'إنشاء'), ('receive', 'استلام'), ('assign', 'إحالة'), ('forward', 'تحويل'), ('progress', 'قيد المعالجة'), ('close', 'إغلاق'), ('escalate', 'تصعيد'), ('note', 'ملاحظة')], max_length=20, verbose_name='الإجراء')),
                ('from_status', models.CharField(max_length=20, verbose_name='الحالة السابقة')),
                ('to_status', models.CharField(max_length=20, verbose_name='الحالة الحالية')),
                ('note', models.TextField(blank=True, verbose_name='ملاحظة')),
                ('actor', models.CharField(max_length=200, verbose_name='تم بواسطة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='التاريخ')),
                ('incident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='ohsms.incident', verbose_name='البلاغ')),
            ],
        ),
        migrations.CreateModel(
            name='Risk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان الخطر')),
                ('description', models.TextField(verbose_name='وصف الخطر')),
                ('severity', models.PositiveSmallIntegerField(verbose_name='الشدة')),
                ('likelihood', models.PositiveSmallIntegerField(verbose_name='الاحتمالية')),
                ('risk_score', models.PositiveSmallIntegerField(editable=False, verbose_name='تقييم الخطر')),
                ('corrective_action', models.TextField(verbose_name='الإجراء التصحيحي')),
                ('preventive_action', models.TextField(verbose_name='الإجراء الوقائي')),
                ('owner_department', models.CharField(max_length=200, verbose_name='الإدارة المسؤولة')),
                ('owner_person', models.CharField(max_length=200, verbose_name='الشخص المفوض')),
                ('contact_channel', models.CharField(max_length=200, verbose_name='قناة التواصل')),
                ('scope_type', models.CharField(choices=[('general', 'عام'), ('branch', 'فرع'), ('department', 'إدارة'), ('section', 'قسم')], max_length=20, verbose_name='نطاق الخطر')),
                ('status', models.CharField(choices=[('draft', 'مسودة'), ('submitted', 'مقدم'), ('approved', 'معتمد'), ('in_progress', 'تحت المعالجة'), ('closed', 'مغلق'), ('rejected', 'مرفوض')], default='draft', max_length=20, verbose_name='حالة الخطر')),
                ('created_by', models.CharField(max_length=200, verbose_name='أُدخل بواسطة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإدخال')),
                ('affected_groups', models.ManyToManyField(to='ohsms.affectedgroup', verbose_name='الفئات المتأثرة')),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ohsms.branch', verbose_name='الفرع')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ohsms.department', verbose_name='الإدارة')),
                ('section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ohsms.section', verbose_name='القسم')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ohsms.riskcategory', verbose_name='فئة الخطر الرئيسية')),
                ('cause', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ohsms.riskcause', verbose_name='سبب الخطر')),
            ],
        ),
        migrations.CreateModel(
            name='RiskNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField(verbose_name='الملاحظة')),
                ('created_by', models.CharField(max_length=200, verbose_name='أُضيفت بواسطة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإضافة')),
                ('risk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='ohsms.risk', verbose_name='الخطر')),
            ],
        ),
        migrations.CreateModel(
            name='RiskSubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='فئة الخطر الفرعية')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_categories', to='ohsms.riskcategory', verbose_name='الفئة الرئيسية')),
            ],
        ),
        migrations.AddField(
            model_name='riskcause',
            name='sub_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='causes', to='ohsms.risksubcategory', verbose_name='الفئة الفرعية'),
        ),
        migrations.AddField(
            model_name='risk',
            name='sub_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ohsms.risksubcategory', verbose_name='فئة الخطر الفرعية'),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('system_admin', 'مدير النظام'), ('system_staff', 'موظف النظام'), ('top_management', 'الإدارة العليا'), ('safety_committee', 'لجنة السلامة'), ('branch_manager', 'مدير فرع'), ('department_manager', 'مدير إدارة'), ('section_manager', 'مدير قسم'), ('safety_coordinator', 'منسق سلامة'), ('employee', 'موظف'), ('external', 'عميل / مورد / مقدم خدمة')], max_length=30, verbose_name='الدور')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ohsms.branch', verbose_name='الفرع')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ohsms.department', verbose_name='الإدارة')),
                ('section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ohsms.section', verbose_name='القسم')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
        ),
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإسناد')),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ohsms.branch', verbose_name='الفرع')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ohsms.department', verbose_name='الإدارة')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ohsms.role', verbose_name='الدور')),
                ('section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ohsms.section', verbose_name='القسم')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
        ),
    ]
