# Generated by Django 6.0 on 2026-01-02 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ohsms', '0006_affectedgroup_formfield_formsubmission_riskcategory_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incident',
            name='handled_at',
        ),
    ]
