# Generated by Django 6.0 on 2026-01-26 11:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ohsms', '0007_remove_incident_handled_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='actor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='تم بواسطة'),
        ),
        migrations.AddField(
            model_name='incident',
            name='handled_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاريخ بدء المعالجة'),
        ),
        migrations.AddField(
            model_name='incident',
            name='risks',
            field=models.ManyToManyField(blank=True, related_name='incidents', to='ohsms.risk', verbose_name='المخاطر المرتبطة'),
        ),
        migrations.AddField(
            model_name='incident',
            name='secret_key',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True, verbose_name='مفتاح متابعة البلاغ السري'),
        ),
        migrations.AlterField(
            model_name='incidentevent',
            name='action',
            field=models.CharField(choices=[('create', 'إنشاء'), ('status_change', 'تغيير حالة'), ('note', 'ملاحظة')], max_length=50, verbose_name='الإجراء'),
        ),
        migrations.AlterField(
            model_name='incidentevent',
            name='actor',
            field=models.CharField(max_length=200, verbose_name='المنفذ'),
        ),
        migrations.AlterField(
            model_name='incidentevent',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الحدث'),
        ),
        migrations.AlterField(
            model_name='incidentevent',
            name='from_status',
            field=models.CharField(blank=True, max_length=50, verbose_name='من حالة'),
        ),
        migrations.AlterField(
            model_name='incidentevent',
            name='to_status',
            field=models.CharField(blank=True, max_length=50, verbose_name='إلى حالة'),
        ),
    ]
