# Generated by Django 6.0 on 2026-01-28 13:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ohsms', '0008_incident_actor_incident_handled_at_incident_risks_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RiskEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('create', 'إنشاء'), ('submit', 'تقديم'), ('approve', 'اعتماد'), ('reject', 'رفض'), ('start_handling', 'بدء المعالجة'), ('close', 'إغلاق'), ('link_incident', 'ربط بلاغ'), ('unlink_incident', 'فك ربط بلاغ')], max_length=50, verbose_name='الإجراء')),
                ('from_status', models.CharField(blank=True, max_length=50, verbose_name='من حالة')),
                ('to_status', models.CharField(blank=True, max_length=50, verbose_name='إلى حالة')),
                ('payload', models.JSONField(blank=True, default=dict, verbose_name='بيانات إضافية')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الحدث')),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='المنفذ')),
                ('risk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='ohsms.risk', verbose_name='الخطر')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
