# Generated by Django 6.0 on 2026-01-28 20:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ohsms', '0009_riskevent'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FormEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('create_template', 'إنشاء نموذج'), ('add_field', 'إضافة حقل'), ('submit', 'تقديم نموذج'), ('deactivate', 'إيقاف نموذج')], max_length=50, verbose_name='الإجراء')),
                ('payload', models.JSONField(blank=True, default=dict, verbose_name='بيانات إضافية')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الحدث')),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='المنفذ')),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='ohsms.formtemplate', verbose_name='النموذج')),
                ('submission', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='ohsms.formsubmission', verbose_name='التقديم')),
            ],
        ),
    ]
