# Generated by Django 6.0 on 2026-01-29 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ohsms', '0010_formevent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incident',
            name='status',
            field=models.CharField(choices=[('open', 'مفتوح'), ('in_progress', 'قيد المعالجة'), ('pending_reporter_confirmation', 'بانتظار موافقة المبلّغ'), ('closed', 'مغلق')], default='open', max_length=50, verbose_name='الحالة'),
        ),
    ]
