# Generated by Django 6.0 on 2026-01-31 15:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ohsms', '0011_alter_incident_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='assigned_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الإحالة'),
        ),
        migrations.AddField(
            model_name='incident',
            name='assigned_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_by_incidents', to=settings.AUTH_USER_MODEL, verbose_name='أُحيل بواسطة'),
        ),
        migrations.AddField(
            model_name='incident',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_incidents', to=settings.AUTH_USER_MODEL, verbose_name='المحال إليه'),
        ),
        migrations.AlterField(
            model_name='incident',
            name='status',
            field=models.CharField(choices=[('new', 'بلاغ جديد'), ('received', 'تم الاستلام'), ('assigned', 'تمت الإحالة'), ('in_progress', 'قيد المعالجة'), ('resolved', 'تمت المعالجة'), ('closed', 'مغلق'), ('escalated', 'مصعّد'), ('open', 'مفتوح (توافق)'), ('pending_reporter_confirmation', 'بانتظار موافقة المبلّغ')], default='open', max_length=50, verbose_name='الحالة'),
        ),
    ]
