# Generated by Django 6.0 on 2026-02-01 13:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ohsms', '0012_incident_assigned_at_incident_assigned_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='executor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='executed_incidents', to=settings.AUTH_USER_MODEL, verbose_name='منفّذ الإجراء التصحيحي'),
        ),
    ]
