# Generated by Django 6.0 on 2026-02-02 11:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ohsms', '0013_incident_executor'),
    ]

    operations = [
        migrations.CreateModel(
            name='RiskReference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان الخطر (مرجعي)')),
                ('description', models.TextField(verbose_name='وصف الخطر (مرجعي)')),
                ('default_severity', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='الشدة الافتراضية')),
                ('default_likelihood', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='الاحتمالية الافتراضية')),
                ('corrective_action', models.TextField(blank=True, verbose_name='الإجراء التصحيحي (مرجعي)')),
                ('preventive_action', models.TextField(blank=True, verbose_name='الإجراء الوقائي (مرجعي)')),
                ('is_active', models.BooleanField(default=True, verbose_name='مفعل')),
                ('created_by', models.CharField(max_length=200, verbose_name='أُدخل بواسطة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإدخال')),
                ('affected_groups', models.ManyToManyField(blank=True, to='ohsms.affectedgroup', verbose_name='الفئات المتأثرة (مرجعي)')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ohsms.riskcategory', verbose_name='الفئة الرئيسية')),
                ('cause', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ohsms.riskcause', verbose_name='السبب')),
                ('sub_category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ohsms.risksubcategory', verbose_name='الفئة الفرعية')),
            ],
        ),
        migrations.AddField(
            model_name='risk',
            name='reference',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='scoped_risks', to='ohsms.riskreference', verbose_name='مرجع الخطر (Reference)'),
        ),
    ]
