# Generated by Django 6.0 on 2026-02-02 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ohsms', '0014_riskreference_risk_reference'),
    ]

    operations = [
        migrations.AddField(
            model_name='formtemplate',
            name='risk_references',
            field=models.ManyToManyField(blank=True, related_name='form_templates', to='ohsms.riskreference', verbose_name='المخاطر المرجعية المرتبطة'),
        ),
    ]
