# Generated by Django 6.0 on 2026-02-02 12:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ohsms', '0015_formtemplate_risk_references'),
    ]

    operations = [
        migrations.AddField(
            model_name='formsubmission',
            name='incident',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='form_submissions', to='ohsms.incident', verbose_name='البلاغ المرتبط'),
        ),
    ]
